import { StyleSheet, Dimensions, Platform } from 'react-native';
const { height, width } = Dimensions.get('window');
export const w = percent => (width * percent) / 100;
export const h = percent => (height * percent) / 100;
export const totalSize = num => (Math.sqrt((height * height) + (width * width)) * num) / 100;

export const WTD = (res) => { return { width: w(res) } }
export const HTD = (res) => { return { height: h(res) } }
export const WT = (res) => { return { width: res } }
export const HT = (res) => { return { height: res } }
export const mWT = (res) => { return { minWidth: res } }
export const mHT = (res) => { return { minHeight: res } }
export const maxWT = (res) => { return { maxWidth: res } }
export const maxHT = (res) => { return { maxHeight: res } }

export const C = StyleSheet.create({
  bgPrimary: { backgroundColor: "#72246C" },
  bgTPH: { backgroundColor: '#00000080' },
  bgTPL: { backgroundColor: '#00000040' },
  bgBlack: { backgroundColor: '#000000' },
  bgTrans: { backgroundColor: 'transparent' },
  bgWhite: { backgroundColor: '#FFFFFF' },
  bgLightGray: { backgroundColor: '#A1A1AA' },
  bgVLGray: { backgroundColor: '#D4D4D8' },
  bgLGray: { backgroundColor: '#E4E4E7' },
  bgScreen: { backgroundColor: '#FFFFFF' },
  bgScreen2: { backgroundColor: '#F4F4F5' },
  bgRed: { backgroundColor: '#FB4949' },
  bgRedDark: { backgroundColor: '#AB3939' },
  bgGreenDark: { backgroundColor: '#308A44' },
  bgGreen: { backgroundColor: '#48BB68' },
  bgInput: { backgroundColor: '#eee' },
  bgOffWhite: { backgroundColor: '#F5F5F5' },
  bgLightBlue: { backgroundColor: '#DCEEF7' },
  bgBlue: { backgroundColor: '#1E76A1' },

  fcBlack: { color: '#000000' },
  fcTab: { color: '#6D3805' },
  fcWhite: { color: '#FFFFFF' },
  fcPrimary: { color: '#72246C' },
  fcLightGray: { color: '#A1A1AA' },
  fcBlue: { color: '#1E76A1' },
  fcRed: { color: '#FB4949' },
  fcGreen: { color: '#48BB68' },
  fcVLGray: { color: '#CBCBCB' },
  fcVLightGray: { color: '#E4E4E7' },
  fcYellow: { color: '#D98405' },
  fcGrey: { color: '#818181' },
  fcDarkGrey: { color: '#807674' },
  fcGrey: { color: '#807674' },
  fcLightGrey: { color: '#BBB4B5' },

  brLightGray: { color: '#A1A1AA' },
  brLight: { borderColor: '#ccc' },
  brLightest: { borderColor: '#eee' },
  brWhite: { borderColor: '#FFFFFF' },
  brBlack: { borderColor: '#000000' },
  brPrimary: { borderColor: '#72246C' },
  brRed: { borderColor: '#FB4949' },
  brGreen: { borderColor: '#48BB68' },

  tcPrimary: { tintColor: '#72246C' },

  feedShimmerBGColor: "#7A7A7A",
  feedShimmerColor: "#A1A1AA",
  searchInputColor: "#F8F8F8",
  searchInputBorderColor: "#E0E0E0",
  searchShimmerBGColor: "#F0F0F0",
  searchShimmerColor: "#FAFAFA",

  colorPrimary: '#72246C',
  colorSecondary: '#CAE1DC',

  colorGradient1: '#72246C',
  colorGradient2: '#381235',

  statusBarContentColor: 'light-content',
  statusBarContentColorDark: 'dark-content',
  statusBarColor: "#FFFFFF",
  transparentColor: '#00000050',
  noColor: "transparent",

  lColor: { color: '#52525B' },
  pColor: { color: '#A1A1AA' },
  fColor: { color: '#333333' },

  white: "#ffffff",
  black: "#000000",
  tabColor: '#6D3805',
  blue: '#2196F3',
  yellow: '#F6B408',
  red: '#FB4949',
  green: '#48BB68',

  strokeColor: '#3399ff',
  fillColor: '#80bfff',

  gray50: "#FAFAFA",
  gray100: "#F4F4F5",
  gray200: "#E4E4E7",
  gray300: "#D4D4D8",
  gray400: "#A1A1AA",
  gray500: "#71717A",
  gray600: "#52525B",
  gray700: "#3F3F46",
  gray800: "#27272A",
  gray900: "#18181B",
});

export const F = StyleSheet.create({
  fsOne: { fontSize: totalSize(1) },
  fsOne1: { fontSize: totalSize(1.1) },
  fsOne2: { fontSize: totalSize(1.2) },
  fsOne3: { fontSize: totalSize(1.3) },
  fsOne4: { fontSize: totalSize(1.4) },
  fsOne5: { fontSize: totalSize(1.5) },
  fsOne6: { fontSize: totalSize(1.6) },
  fsOne7: { fontSize: totalSize(1.7) },
  fsOne8: { fontSize: totalSize(1.8) },
  fsOne9: { fontSize: totalSize(1.9) },
  fsTwo: { fontSize: totalSize(2) },
  fsTwo1: { fontSize: totalSize(2.1) },
  fsTwo2: { fontSize: totalSize(2.2) },
  fsTwo3: { fontSize: totalSize(2.3) },
  fsTwo4: { fontSize: totalSize(2.4) },
  fsTwo5: { fontSize: totalSize(2.5) },
  fsTwo6: { fontSize: totalSize(2.6) },
  fsTwo7: { fontSize: totalSize(2.7) },
  fsTwo8: { fontSize: totalSize(2.8) },
  fsTwo9: { fontSize: totalSize(2.9) },
  fsThree: { fontSize: totalSize(3) },
  fsThree1: { fontSize: totalSize(3.1) },
  fsThree2: { fontSize: totalSize(3.2) },
  fsThree3: { fontSize: totalSize(3.3) },
  fsThree4: { fontSize: totalSize(3.4) },
  fsThree5: { fontSize: totalSize(3.5) },
  fsThree6: { fontSize: totalSize(3.6) },
  fsThree7: { fontSize: totalSize(3.7) },
  fsThree8: { fontSize: totalSize(3.8) },
  fsThree9: { fontSize: totalSize(3.9) },
  fsFour: { fontSize: totalSize(4) },
  fsFour5: { fontSize: totalSize(4.5) },

  lh12: { lineHeight: 12 },
  lh15: { lineHeight: 15 },
  lh16: { lineHeight: 16 },
  lh17: { lineHeight: 17 },
  lh18: { lineHeight: 18 },
  lh20: { lineHeight: 20 },
  lh22: { lineHeight: 22 },
  lh24: { lineHeight: 24 },
  lh26: { lineHeight: 26 },
  lh28: { lineHeight: 28 },
  lh30: { lineHeight: 30 },

  fwN: { fontWeight: 'normal' },
  fwB: { fontWeight: 'bold' },
  fw1: { fontWeight: '100' },
  fw2: { fontWeight: '200' },
  fw3: { fontWeight: '300' },
  fw4: { fontWeight: '400' },
  fw5: { fontWeight: '500' },
  fw6: { fontWeight: '600' },
  fw7: { fontWeight: '700' },
  fw8: { fontWeight: '800' },
  fw9: { fontWeight: '900' },

  ffR: { fontFamily: 'OpenSans-Regular' },
  ffL: { fontFamily: 'OpenSans-Light' },
  ffM: { fontFamily: 'OpenSans-Medium' },
  ffS: { fontFamily: 'OpenSans-SemiBold' },
  ffB: { fontFamily: 'OpenSans-Bold' },
  ffI: { fontFamily: 'italic' },

  regularFont: 'OpenSans-Regular',
  lightFont: 'OpenSans-Light',
  mediumFont: 'OpenSans-Medium',
  semiBoldFont: 'OpenSans-SemiBold',
  boldFont: 'OpenSans-Bold',

  tDL: { textDecorationLine: 'underline' },
  tC: { textDecorationLine: 'line-through', textDecorationStyle: 'solid' }

});

export const L = StyleSheet.create({
  headerView: {
    alignSelf: 'center',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: w(3),
    height: h(8),
    backgroundColor: C.white,
    marginTop: Platform.OS == 'ios' ? h(6.5) : 0,
  },

  // input 
  vwInput: {
    marginTop: h(5),
    flexDirection: 'row',
    paddingHorizontal: 5,
    alignItems: 'center',
    alignSelf: "center",
    backgroundColor: C.white,
    borderWidth: 0.3,
    borderColor: C.gray200,
    paddingVertical: 1,
    borderRadius: 5,
    minHeight: h(7),
    width: '100%',
  },
  input: {
    fontSize: F.oneSeven,
    color: C.fcBlackLight,
    paddingVertical: 1,
    width: '90%',
    fontFamily: F.mediumFont,
    marginLeft: 5,
  },
  ic_size: 25,
  ic_color: C.gray600,
  placeholderTextColor: C.gray300,
  selectionColor: C.colorPrimary,

  odd: { flexDirection: 'row-reverse' },
  even: { flexDirection: 'row' },

  opc1: { opacity: 1 },
  opc2: { opacity: 0.2 },
  opc3: { opacity: 0.3 },
  opc4: { opacity: 0.4 },
  opc5: { opacity: 0.5 },
  opc6: { opacity: 0.6 },
  opc7: { opacity: 0.7 },
  opc8: { opacity: 0.8 },

  // display position bottom
  dpR: { position: 'relative' },
  dpA: { position: 'absolute' },
  dpATR5: { position: 'absolute', top: 5, right: 5 },
  dpATR10: { position: 'absolute', top: 10, right: 10 },
  dpARL: { position: 'absolute', left: 0, right: 0, bottom: 0 },

  shadow2: { elevation: 2 }, // For IOS shadowColor/shadowOffset/shadowOpacity/shadowRadius
  shadow4: { elevation: 4 }, // For IOS shadowColor/shadowOffset/shadowOpacity/shadowRadius
  shadow6: { elevation: 6 }, // For IOS shadowColor/shadowOffset/shadowOpacity/shadowRadius
  shadow8: { elevation: 8 }, // For IOS shadowColor/shadowOffset/shadowOpacity/shadowRadius
  shadow10: { elevation: 10 }, // For IOS shadowColor/shadowOffset/shadowOpacity/shadowRadius    

  br0: { borderWidth: 0 },
  br05: { borderWidth: 0.5 },
  br1: { borderWidth: 1 },
  br2: { borderWidth: 2 },
  br3: { borderWidth: 3 },
  brB05: { borderBottomWidth: 1 / 2 },
  brB1: { borderBottomWidth: 1 },
  brB2: { borderBottomWidth: 2 },
  brB3: { borderBottomWidth: 3 },
  brL1: { borderLeftWidth: 1 },
  brL2: { borderLeftWidth: 2 },
  brL3: { borderLeftWidth: 3 },
  brT1: { borderTopWidth: 1 },
  brT2: { borderTopWidth: 2 },
  brT3: { borderTopWidth: 3 },
  brR1: { borderRightWidth: 1 },
  brR2: { borderRightWidth: 2 },
  brR3: { borderRightWidth: 3 },

  bR0: { borderRadius: 0 },
  bR1: { borderRadius: 1 },
  bR2: { borderRadius: 2 },
  bR4: { borderRadius: 4 },
  bR5: { borderRadius: 5 },
  bR8: { borderRadius: 8 },
  bR10: { borderRadius: 10 },
  bR15: { borderRadius: 15 },
  bR20: { borderRadius: 20 },
  bR25: { borderRadius: 25 },
  bR30: { borderRadius: 30 },
  bR40: { borderRadius: 40 },
  bR50: { borderRadius: 50 },
  bR60: { borderRadius: 60 },
  bR80: { borderRadius: 80 },
  bR100: { borderRadius: 200 / 2 },

  bRBR240: { borderBottomRightRadius: 480 / 2 },

  bRTR50: { borderTopRightRadius: 50 },
  bRTR40: { borderTopRightRadius: 40 },
  bRTR30: { borderTopRightRadius: 30 },
  bRTR20: { borderTopRightRadius: 20 },
  bRBR20: { borderBottomRightRadius: 20 },
  bRTR15: { borderTopRightRadius: 15 },
  bRBR15: { borderBottomRightRadius: 15 },
  bRTR10: { borderTopRightRadius: 10 },
  bRBR10: { borderBottomRightRadius: 10 },
  bRTR5: { borderTopRightRadius: 5 },
  bRBR5: { borderBottomRightRadius: 5 },

  bLTR50: { borderTopLeftRadius: 50 },
  bLBR50: { borderBottomLeftRadius: 50 },
  bLTR40: { borderTopLeftRadius: 40 },
  bLBR40: { borderBottomLeftRadius: 40 },
  bLTR30: { borderTopLeftRadius: 30 },
  bLBR30: { borderBottomLeftRadius: 30 },
  bLTR20: { borderTopLeftRadius: 20 },
  bLBR20: { borderBottomLeftRadius: 20 },
  bLBR10: { borderBottomLeftRadius: 10 },
  bLBR15: { borderBottomLeftRadius: 15 },

  p0: { padding: 0 },
  p3: { padding: 3 },
  p5: { padding: 5 },
  p8: { padding: 8 },
  p10: { padding: 10 },
  p12: { padding: 12 },
  p15: { padding: 15 },
  p18: { padding: 18 },
  p20: { padding: 20 },
  p22: { padding: 22 },
  p25: { padding: 25 },
  p30: { padding: 30 },

  pB0: { paddingBottom: 0 },
  pB3: { paddingBottom: 3 },
  pB5: { paddingBottom: 5 },
  pB8: { paddingBottom: 8 },
  pB10: { paddingBottom: 10 },
  pB12: { paddingBottom: 12 },
  pB15: { paddingBottom: 15 },
  pB18: { paddingBottom: 18 },
  pB20: { paddingBottom: 20 },
  pB22: { paddingBottom: 22 },
  pB25: { paddingBottom: 25 },

  pL0: { paddingLeft: 0 },
  pL5: { paddingLeft: 5 },
  pL8: { paddingLeft: 8 },
  pL10: { paddingLeft: 10 },
  pL12: { paddingLeft: 12 },
  pL15: { paddingLeft: 15 },
  pL18: { paddingLeft: 18 },
  pL20: { paddingLeft: 20 },
  pL22: { paddingLeft: 22 },
  pL25: { paddingLeft: 25 },

  pT0: { paddingTop: 0 },
  pT5: { paddingTop: 5 },
  pT8: { paddingTop: 8 },
  pT10: { paddingTop: 10 },
  pT12: { paddingTop: 12 },
  pT15: { paddingTop: 15 },
  pT18: { paddingTop: 18 },
  pT20: { paddingTop: 20 },
  pT22: { paddingTop: 22 },
  pT25: { paddingTop: 25 },

  pR0: { paddingRight: 0 },
  pR5: { paddingRight: 5 },
  pR8: { paddingRight: 8 },
  pR10: { paddingRight: 10 },
  pR12: { paddingRight: 12 },
  pR15: { paddingRight: 15 },
  pR18: { paddingRight: 18 },
  pR20: { paddingRight: 20 },
  pR22: { paddingRight: 22 },
  pR25: { paddingRight: 25 },

  pH0: { paddingHorizontal: 0 },
  pH2: { paddingHorizontal: 2, },
  pH5: { paddingHorizontal: 5, },
  pH6: { paddingHorizontal: 6, },
  pH8: { paddingHorizontal: 8, },
  pH10: { paddingHorizontal: 10 },
  pH12: { paddingHorizontal: 12 },
  pH15: { paddingHorizontal: 15 },
  pH18: { paddingHorizontal: 18 },
  pH20: { paddingHorizontal: 20 },
  pH22: { paddingHorizontal: 22 },
  pH25: { paddingHorizontal: 25 },

  pV0: { paddingVertical: 0 },
  pV2: { paddingVertical: 2 },
  pV4: { paddingVertical: 4 },
  pV5: { paddingVertical: 5 },
  pV8: { paddingVertical: 8 },
  pV10: { paddingVertical: 10 },
  pV12: { paddingVertical: 12 },
  pV15: { paddingVertical: 15 },
  pV18: { paddingVertical: 18 },
  pV20: { paddingVertical: 20 },
  pV22: { paddingVertical: 22 },
  pV25: { paddingVertical: 25 },
  pV30: { paddingVertical: 30 },
  pV35: { paddingVertical: 35 },
  pV40: { paddingVertical: 40 },

  mH0: { marginHorizontal: 0 },
  mH3: { marginHorizontal: 3 },
  mH5: { marginHorizontal: 5 },
  mH6: { marginHorizontal: 6 },
  mH7: { marginHorizontal: 7 },
  mH10: { marginHorizontal: 10 },
  mH15: { marginHorizontal: 15 },
  mH16: { marginHorizontal: 16 },
  mH17: { marginHorizontal: 17 },
  mH18: { marginHorizontal: 18 },
  mH19: { marginHorizontal: 19 },
  mH20: { marginHorizontal: 20 },
  mH25: { marginHorizontal: 25 },
  mH30: { marginHorizontal: 30 },

  mV0: { marginVertical: 0 },
  mV2: { marginVertical: 2 },
  mV5: { marginVertical: 5 },
  mV10: { marginVertical: 10 },
  mV15: { marginVertical: 15 },
  mV20: { marginVertical: 20 },
  mV25: { marginVertical: 25 },
  mV30: { marginVertical: 30 },

  m0: { margin: 0 },
  m5: { margin: 5 },
  m8: { margin: 8 },
  m10: { margin: 10 },
  m12: { margin: 12 },
  m15: { margin: 15 },
  m18: { margin: 18 },
  m20: { margin: 20 },
  m22: { margin: 22 },
  m25: { margin: 25 },

  mB0: { marginBottom: 0 },
  mB1: { marginBottom: 1 },
  mB2: { marginBottom: 2 },
  mB3: { marginBottom: 3 },
  mB5: { marginBottom: 5 },
  mB8: { marginBottom: 8 },
  mB10: { marginBottom: 10 },
  mB12: { marginBottom: 12 },
  mB15: { marginBottom: 15 },
  mB18: { marginBottom: 18 },
  mB20: { marginBottom: 20 },
  mB22: { marginBottom: 22 },
  mB25: { marginBottom: 25 },
  mB30: { marginBottom: 30 },

  mL0: { marginLeft: 0 },
  mL2: { marginLeft: 2 },
  mL3: { marginLeft: 3 },
  mL5: { marginLeft: 5 },
  mL8: { marginLeft: 8 },
  mL10: { marginLeft: 10 },
  mL12: { marginLeft: 12 },
  mL15: { marginLeft: 15 },
  mL18: { marginLeft: 18 },
  mL20: { marginLeft: 20 },
  mL22: { marginLeft: 22 },
  mL25: { marginLeft: 25 },
  mL30: { marginLeft: 30 },
  mL35: { marginLeft: 35 },
  mL40: { marginLeft: 40 },
  mL50: { marginLeft: 50 },
  mL70: { marginLeft: 70 },
  mL100: { marginLeft: 100 },

  mT0: { marginTop: 0 },
  mT1: { marginTop: 1 },
  mT2: { marginTop: 2 },
  mT5: { marginTop: 5 },
  mT6: { marginTop: 6 },
  mT8: { marginTop: 8 },
  mT10: { marginTop: 10 },
  mT12: { marginTop: 12 },
  mT15: { marginTop: 15 },
  mT16: { marginTop: 16 },
  mT17: { marginTop: 17 },
  mT18: { marginTop: 18 },
  mT19: { marginTop: 19 },
  mT20: { marginTop: 20 },
  mT22: { marginTop: 22 },
  mT25: { marginTop: 25 },
  mT30: { marginTop: 30 },
  mT35: { marginTop: 35 },
  mT45: { marginTop: 45 },

  mR0: { marginRight: 0 },
  mR5: { marginRight: 5 },
  mR8: { marginRight: 8 },
  mR10: { marginRight: 10 },
  mR12: { marginRight: 12 },
  mR15: { marginRight: 15 },
  mR18: { marginRight: 18 },
  mR20: { marginRight: 20 },
  mR22: { marginRight: 22 },
  mR25: { marginRight: 25 },
  mR30: { marginRight: 30 },
  mR45: { marginRight: 45 },
  mR50: { marginRight: 50 },

  taA: { textAlign: 'auto' },
  taL: { textAlign: 'left' },
  taR: { textAlign: 'right' },
  taC: { textAlign: 'center' },
  taJ: { textAlign: "justify" },

  taT: { textAlignVertical: 'top' },
  taB: { textAlignVertical: 'bottom' },
  taA: { textAlignVertical: 'auto' },
  taVC: { textAlignVertical: 'center' },
  taVT: { textAlignVertical: 'top' },
  taVB: { textAlignVertical: 'bottom' },
  taVA: { textAlignVertical: 'auto' },

  jcC: { justifyContent: 'center' },
  jcT: { justifyContent: 'flex-start' },
  jcB: { justifyContent: 'flex-end' },
  jcSA: { justifyContent: 'space-around' },
  jcSB: { justifyContent: 'space-between' },
  jcSE: { justifyContent: 'space-evenly' },

  aiB: { alignItems: 'baseline' },
  aiC: { alignItems: 'center' },
  aiL: { alignItems: 'flex-start' },
  aiR: { alignItems: 'flex-end' },
  aiS: { alignItems: 'stretch' },

  asA: { alignSelf: 'auto' },
  asL: { alignSelf: 'flex-start' },
  asR: { alignSelf: 'flex-end' },
  asB: { alignSelf: 'baseline' },
  asC: { alignSelf: 'center' },
  asS: { alignSelf: 'stretch' },

  f1: { flex: 1 },
  f2: { flex: 2 },
  f3: { flex: 3 },
  f4: { flex: 4 },
  f5: { flex: 5 },
  f6: { flex: 6 },
  f7: { flex: 7 },
  f8: { flex: 8 },
  f9: { flex: 9 },
  f10: { flex: 10 },
  f11: { flex: 11 },
  f12: { flex: 12 },

  fdR: { flexDirection: 'row' },
  fdRR: { flexDirection: 'row-reverse' },
  fdC: { flexDirection: 'column' },
  fdCR: { flexDirection: 'column-reverse' },
  fw: { flexWrap: 'wrap' },
  fS: { flexShrink: 1 },
  fg: { flexGrow: 1 },

  rMCe: { resizeMode: 'center' },
  rMCo: { resizeMode: 'cover' },
  rMCon: { resizeMode: 'contain' },
  rMR: { resizeMode: 'repeat' },
  rMS: { resizeMode: 'stretch' },

  card: {
    elevation: 2,
    shadowOpacity: 1,
    shadowColor: Platform.OS == 'ios' ? '#E4E4E7' : '#A1A1AA',
    shadowOffset: { width: 1, height: 1 },
    shadowRadius: 1,
  },
  oc5: { opacity: 0.5 },
  oc1: { opacity: 1 },

  activeOpacity: 0.70,
});

export const nDText = [F.fsOne6, F.ffM, L.taC, C.lColor, L.mV10]